//! Linux x86-64 ABI entry points implemented in assembly.

std::arch::global_asm!(
    ".text",
    ".extern __sigsetjmp",
    ".global winrun_call_guest_with_signal_recovery",
    ".type winrun_call_guest_with_signal_recovery,@function",
    "winrun_call_guest_with_signal_recovery:",
    "push rbp",
    "push rbx",
    "push rsi",
    "push rdi",
    "push r12",
    "push r13",
    "push r14",
    "push r15",
    "sub rsp, 40",
    // Seventh SysV argument: the three Win64 register arguments. Keep its
    // pointer above the 32-byte shadow space across sigsetjmp.
    "mov rax, [rsp + 112]",
    "mov [rsp + 32], rax",
    "mov r13, rdi",
    "mov r14, rsi",
    "mov r12, rdx",
    "mov r15, rcx",
    "mov rbx, r8",
    "mov rbp, r9",
    "mov rdi, r14",
    "mov esi, 1",
    "call __sigsetjmp@PLT",
    "test eax, eax",
    "jnz 1f",
    "mov rax, [rsp + 32]",
    "mov rcx, [rax]",
    "mov rdx, [rax + 8]",
    "mov r8, [rax + 16]",
    "call r13",
    "mov dword ptr [r12], eax",
    "xor eax, eax",
    "jmp 2f",
    "1:",
    "mov rdi, rbx",
    "call r15",
    "cmp eax, 1",
    "je 3f",
    "mov dword ptr [r12], eax",
    "mov eax, 1",
    "jmp 2f",
    "3:",
    "mov rdi, rbp",
    "call setcontext@PLT",
    "test eax, eax",
    "js 4f",
    "mov dword ptr [r12], eax",
    "xor eax, eax",
    "jmp 2f",
    "4:",
    "mov dword ptr [r12], 0xc0000005",
    "mov eax, 1",
    "2:",
    "add rsp, 40",
    "pop r15",
    "pop r14",
    "pop r13",
    "pop r12",
    "pop rdi",
    "pop rsi",
    "pop rbx",
    "pop rbp",
    "ret",
    ".size winrun_call_guest_with_signal_recovery, .-winrun_call_guest_with_signal_recovery",
    ".global winrun_native_rtl_capture_context",
    ".type winrun_native_rtl_capture_context,@function",
    "winrun_native_rtl_capture_context:",
    "mov [rcx + 208], r11",
    "mov r11, rcx",
    "mov qword ptr [r11 + 0], 0",
    "mov qword ptr [r11 + 8], 0",
    "mov qword ptr [r11 + 16], 0",
    "mov qword ptr [r11 + 24], 0",
    "mov qword ptr [r11 + 32], 0",
    "mov qword ptr [r11 + 40], 0",
    "mov dword ptr [r11 + 48], 0x0010001f",
    "mov [r11 + 120], rax",
    "mov [r11 + 128], rcx",
    "mov [r11 + 136], rdx",
    "mov [r11 + 144], rbx",
    "lea rax, [rsp + 8]",
    "mov [r11 + 152], rax",
    "mov [r11 + 160], rbp",
    "mov [r11 + 168], rsi",
    "mov [r11 + 176], rdi",
    "mov [r11 + 184], r8",
    "mov [r11 + 192], r9",
    "mov [r11 + 200], r10",
    "mov [r11 + 216], r12",
    "mov [r11 + 224], r13",
    "mov [r11 + 232], r14",
    "mov [r11 + 240], r15",
    "mov rax, [rsp]",
    "mov [r11 + 248], rax",
    "pushfq",
    "pop rax",
    "mov [r11 + 68], eax",
    "mov ax, cs",
    "mov [r11 + 56], ax",
    "mov ax, ds",
    "mov [r11 + 58], ax",
    "mov ax, es",
    "mov [r11 + 60], ax",
    "mov ax, fs",
    "mov [r11 + 62], ax",
    "mov ax, gs",
    "mov [r11 + 64], ax",
    "mov ax, ss",
    "mov [r11 + 66], ax",
    "mov qword ptr [r11 + 72], 0",
    "mov qword ptr [r11 + 80], 0",
    "mov qword ptr [r11 + 88], 0",
    "mov qword ptr [r11 + 96], 0",
    "mov qword ptr [r11 + 104], 0",
    "mov qword ptr [r11 + 112], 0",
    "stmxcsr [r11 + 52]",
    "fxsave64 [r11 + 256]",
    "lea rdi, [r11 + 768]",
    "xor eax, eax",
    "mov ecx, 58",
    "rep stosq",
    "mov rdi, [r11 + 176]",
    "ret",
    ".size winrun_native_rtl_capture_context, .-winrun_native_rtl_capture_context",
    // RaiseException, RtlUnwindEx, and RtlUnwind capture their caller's
    // CONTEXT (non-volatile registers as at entry, Rsp above the return
    // address, Rip the return address) in a 16-byte-aligned frame slot, then
    // pass it to Rust after the original arguments. RaiseException passes
    // the context as its fifth argument; the unwind entries pass the
    // caller's OriginalContext (or null) fifth and the capture sixth.
    ".global winrun_native_raise_exception",
    ".type winrun_native_raise_exception,@function",
    "winrun_native_raise_exception:",
    "mov [rsp + 8], rcx",
    "mov [rsp + 16], rdx",
    "mov [rsp + 24], r8",
    "mov [rsp + 32], r9",
    "sub rsp, 0x518",
    "lea rcx, [rsp + 0x40]",
    "call winrun_native_rtl_capture_context",
    "lea rax, [rsp + 0x520]",
    "mov [rsp + 0x40 + 152], rax",
    "mov rax, [rsp + 0x518]",
    "mov [rsp + 0x40 + 248], rax",
    "mov rcx, [rsp + 0x520]",
    "mov rdx, [rsp + 0x528]",
    "mov r8, [rsp + 0x530]",
    "mov r9, [rsp + 0x538]",
    "lea rax, [rsp + 0x40]",
    "mov [rsp + 0x20], rax",
    "lea rax, [rsp + 0x40]",
    "mov [rsp + 0x28], rax",
    "call winrun_raise_exception_with_context",
    "add rsp, 0x518",
    "ret",
    ".size winrun_native_raise_exception, .-winrun_native_raise_exception",
    // _CxxThrowException(object, throw_info): capture the thrower's context
    // like RaiseException, then raise the C++ exception from Rust.
    ".global winrun_native_cxx_throw_exception",
    ".type winrun_native_cxx_throw_exception,@function",
    "winrun_native_cxx_throw_exception:",
    "mov [rsp + 8], rcx",
    "mov [rsp + 16], rdx",
    "sub rsp, 0x518",
    "lea rcx, [rsp + 0x40]",
    "call winrun_native_rtl_capture_context",
    "lea rax, [rsp + 0x520]",
    "mov [rsp + 0x40 + 152], rax",
    "mov rax, [rsp + 0x518]",
    "mov [rsp + 0x40 + 248], rax",
    "mov rcx, [rsp + 0x520]",
    "mov rdx, [rsp + 0x528]",
    "lea r8, [rsp + 0x40]",
    "call winrun_cxx_throw_with_context",
    "add rsp, 0x518",
    "ret",
    ".size winrun_native_cxx_throw_exception, .-winrun_native_cxx_throw_exception",
    // __RTDynamicCast(object, vfdelta, source, target, is_reference) and
    // __RTtypeid(object): capture the caller's context (for a bad_cast or
    // bad_typeid throw) and continue in Rust; the result returns in rax.
    ".global winrun_native_rt_dynamic_cast",
    ".type winrun_native_rt_dynamic_cast,@function",
    "winrun_native_rt_dynamic_cast:",
    "mov [rsp + 8], rcx",
    "mov [rsp + 16], rdx",
    "mov [rsp + 24], r8",
    "mov [rsp + 32], r9",
    "sub rsp, 0x518",
    "lea rcx, [rsp + 0x40]",
    "call winrun_native_rtl_capture_context",
    "lea rax, [rsp + 0x520]",
    "mov [rsp + 0x40 + 152], rax",
    "mov rax, [rsp + 0x518]",
    "mov [rsp + 0x40 + 248], rax",
    "mov rcx, [rsp + 0x520]",
    "mov rdx, [rsp + 0x528]",
    "mov r8, [rsp + 0x530]",
    "mov r9, [rsp + 0x538]",
    "mov rax, [rsp + 0x540]",
    "mov [rsp + 0x20], rax",
    "lea rax, [rsp + 0x40]",
    "mov [rsp + 0x28], rax",
    "call winrun_rt_dynamic_cast_with_context",
    "add rsp, 0x518",
    "ret",
    ".size winrun_native_rt_dynamic_cast, .-winrun_native_rt_dynamic_cast",
    ".global winrun_native_rt_typeid",
    ".type winrun_native_rt_typeid,@function",
    "winrun_native_rt_typeid:",
    "mov [rsp + 8], rcx",
    "sub rsp, 0x518",
    "lea rcx, [rsp + 0x40]",
    "call winrun_native_rtl_capture_context",
    "lea rax, [rsp + 0x520]",
    "mov [rsp + 0x40 + 152], rax",
    "mov rax, [rsp + 0x518]",
    "mov [rsp + 0x40 + 248], rax",
    "mov rcx, [rsp + 0x520]",
    "lea rdx, [rsp + 0x40]",
    "call winrun_rt_typeid_with_context",
    "add rsp, 0x518",
    "ret",
    ".size winrun_native_rt_typeid, .-winrun_native_rt_typeid",
    ".global winrun_native_rtl_unwind_ex",
    ".type winrun_native_rtl_unwind_ex,@function",
    "winrun_native_rtl_unwind_ex:",
    "mov [rsp + 8], rcx",
    "mov [rsp + 16], rdx",
    "mov [rsp + 24], r8",
    "mov [rsp + 32], r9",
    "sub rsp, 0x518",
    "lea rcx, [rsp + 0x40]",
    "call winrun_native_rtl_capture_context",
    "lea rax, [rsp + 0x520]",
    "mov [rsp + 0x40 + 152], rax",
    "mov rax, [rsp + 0x518]",
    "mov [rsp + 0x40 + 248], rax",
    "mov rcx, [rsp + 0x520]",
    "mov rdx, [rsp + 0x528]",
    "mov r8, [rsp + 0x530]",
    "mov r9, [rsp + 0x538]",
    "mov rax, [rsp + 0x540]",
    "mov [rsp + 0x20], rax",
    "lea rax, [rsp + 0x40]",
    "mov [rsp + 0x28], rax",
    "call winrun_rtl_unwind_with_context",
    "add rsp, 0x518",
    "ret",
    ".size winrun_native_rtl_unwind_ex, .-winrun_native_rtl_unwind_ex",
    ".global winrun_native_rtl_unwind",
    ".type winrun_native_rtl_unwind,@function",
    "winrun_native_rtl_unwind:",
    "mov [rsp + 8], rcx",
    "mov [rsp + 16], rdx",
    "mov [rsp + 24], r8",
    "mov [rsp + 32], r9",
    "sub rsp, 0x518",
    "lea rcx, [rsp + 0x40]",
    "call winrun_native_rtl_capture_context",
    "lea rax, [rsp + 0x520]",
    "mov [rsp + 0x40 + 152], rax",
    "mov rax, [rsp + 0x518]",
    "mov [rsp + 0x40 + 248], rax",
    "mov rcx, [rsp + 0x520]",
    "mov rdx, [rsp + 0x528]",
    "mov r8, [rsp + 0x530]",
    "mov r9, [rsp + 0x538]",
    "mov qword ptr [rsp + 0x20], 0",
    "lea rax, [rsp + 0x40]",
    "mov [rsp + 0x28], rax",
    "call winrun_rtl_unwind_with_context",
    "add rsp, 0x518",
    "ret",
    ".size winrun_native_rtl_unwind, .-winrun_native_rtl_unwind",
    // Load every register from a CONTEXT (rcx) and continue at its Rip,
    // with Rsp from the context. Floating-point and SSE state come from the
    // FXSAVE area.
    ".global winrun_native_rtl_restore_context",
    ".type winrun_native_rtl_restore_context,@function",
    "winrun_native_rtl_restore_context:",
    "mov rax, rcx",
    "fxrstor64 [rax + 256]",
    "mov rcx, [rax + 152]",
    "sub rcx, 8",
    "mov rdx, [rax + 248]",
    "mov [rcx], rdx",
    "mov rbx, [rax + 144]",
    "mov rbp, [rax + 160]",
    "mov rsi, [rax + 168]",
    "mov rdi, [rax + 176]",
    "mov r8, [rax + 184]",
    "mov r9, [rax + 192]",
    "mov r10, [rax + 200]",
    "mov r11, [rax + 208]",
    "mov r12, [rax + 216]",
    "mov r13, [rax + 224]",
    "mov r14, [rax + 232]",
    "mov r15, [rax + 240]",
    "mov rdx, [rax + 136]",
    "mov rsp, rcx",
    "mov rcx, [rax + 128]",
    "mov rax, [rax + 120]",
    "ret",
    ".size winrun_native_rtl_restore_context, .-winrun_native_rtl_restore_context",
);
unsafe extern "win64" {
    pub(super) fn winrun_native_rtl_capture_context(context: *mut u8);
    pub(super) fn winrun_native_raise_exception(code: u32, flags: u32, count: u32, arguments: *const u64);
    pub(super) fn winrun_native_cxx_throw_exception(object: u64, throw_info: u64);
    pub(super) fn winrun_native_rt_dynamic_cast(object: u64, vf_delta: i32, source: u64, target: u64, is_reference: i32) -> u64;
    pub(super) fn winrun_native_rt_typeid(object: u64) -> u64;
    pub(super) fn winrun_native_rtl_unwind_ex(
        target_frame: u64,
        target_ip: u64,
        record: *mut u8,
        return_value: u64,
        original_context: *mut u8,
        history_table: *mut u8,
    );
    pub(super) fn winrun_native_rtl_unwind(target_frame: u64, target_ip: u64, record: *mut u8, return_value: u64);
    pub(super) fn winrun_native_rtl_restore_context(context: *mut u8) -> !;
}

unsafe extern "C" {
    pub(super) fn winrun_call_guest_with_signal_recovery(
        entry: u64,
        signal_jump_buffer: *mut core::ffi::c_void,
        guest_exit_code: *mut u32,
        fault_dispatcher: extern "C" fn(*const core::ffi::c_void) -> i32,
        fault_slot: *const core::ffi::c_void,
        linux_context: *const core::ffi::c_void,
        arguments: *const u64,
    ) -> i32;
}
