//! The .NET surface installer scripts lean on: `Add-Type` P/Invoke
//! declarations answered by built-in implementations of the Win32
//! functions they name, `[Type]` casts, and the `-as` operator.
use super::*;

/// A type declared by `Add-Type -MemberDefinition`: its full name and the
/// `extern` functions it imports, as (lowercased DLL file, function name).
#[derive(Clone, Debug, PartialEq)]
pub struct AddedType {
    pub name: String,
    pub methods: Vec<(String, String)>,
}

/// Namespace PowerShell gives `Add-Type -MemberDefinition` without one.
const DEFAULT_NAMESPACE: &str = "Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes";

/// The `[DllImport("x")] ... extern T Name(...)` declarations of a member
/// definition. C# members other than imports are not supported.
pub(super) fn parse_member_definition(text: &str) -> Result<Vec<(String, String)>, String> {
    let mut methods = Vec::new();
    let mut rest = text;
    while let Some(at) = rest.find("DllImport") {
        rest = &rest[at + "DllImport".len()..];
        let open = rest
            .find('"')
            .ok_or("Add-Type: DllImport needs a library name")?;
        let close = rest[open + 1..]
            .find('"')
            .ok_or("Add-Type: unterminated DllImport library name")?;
        let mut dll = rest[open + 1..open + 1 + close].to_ascii_lowercase();
        if !dll.ends_with(".dll") {
            dll.push_str(".dll");
        }
        rest = &rest[open + 1 + close..];
        let ext = rest
            .find("extern ")
            .ok_or("Add-Type: DllImport without an extern method")?;
        let paren = rest[ext..]
            .find('(')
            .ok_or("Add-Type: extern method without parameters")?;
        let head = rest[ext + "extern ".len()..ext + paren].trim();
        let name = head
            .rsplit(char::is_whitespace)
            .next()
            .filter(|n| !n.is_empty() && n.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'))
            .ok_or("Add-Type: cannot read the extern method name")?;
        methods.push((dll, name.to_string()));
        rest = &rest[ext + paren..];
    }
    if methods.is_empty() {
        return Err("Add-Type: only [DllImport] extern member definitions are supported".into());
    }
    Ok(methods)
}

/// `[Type]` alone (a type literal, not a static member access): the name.
pub(super) fn type_literal(text: &str) -> Option<&str> {
    let inner = text.trim().strip_prefix('[')?.strip_suffix(']')?;
    let name = inner.strip_suffix("[]").unwrap_or(inner);
    (!name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '_'))
    .then_some(inner)
}

/// `[Type]value` written without a space: (type, value text).
pub(super) fn attached_cast(text: &str) -> Option<(&str, &str)> {
    let inner = text.strip_prefix('[')?;
    let end = inner.find(']')?;
    let rest = &inner[end + 1..];
    if rest.is_empty() || rest.starts_with("::") || rest.starts_with(['.', '[']) {
        return None;
    }
    type_literal(&text[..end + 2]).map(|t| (t, rest))
}

/// Built-in type names `-as [Type]` and casts recognize.
const KNOWN_TYPES: &[&str] = &[
    "string", "int", "int32", "long", "int64", "uint32", "uint64", "byte", "double", "bool",
    "boolean", "char", "intptr", "uintptr", "type", "object", "array", "ref", "environment",
    "guid", "regex", "datetime", "version",
];

fn bare_type(typ: &str) -> String {
    let t = typ.trim().to_ascii_lowercase();
    t.strip_prefix("system.").map(str::to_string).unwrap_or(t)
}

impl Interpreter<'_> {
    /// `Add-Type`: register `-MemberDefinition` imports under
    /// `Namespace.Name` (`-PassThru` outputs the type). Assembly loads are
    /// accepted; compiling C# `-TypeDefinition` source is not supported.
    pub(super) fn cmd_add_type(&mut self, args: &[String]) -> Result<(), String> {
        let (named, positional) = parse_params(
            args,
            &[
                "memberdefinition",
                "name",
                "namespace",
                "passthru",
                "typedefinition",
                "assemblyname",
                "usingnamespace",
                "language",
                "path",
            ],
        )?;
        if named.contains_key("typedefinition") || named.contains_key("path") {
            return Err("Add-Type: compiling C# source is not supported".to_string());
        }
        let Some(definition) = named.get("memberdefinition") else {
            if named.contains_key("assemblyname") || !positional.is_empty() {
                return Ok(());
            }
            return Err("Add-Type: missing -MemberDefinition".to_string());
        };
        let name = named
            .get("name")
            .ok_or("Add-Type: -MemberDefinition needs -Name")?;
        let namespace = named
            .get("namespace")
            .map(String::as_str)
            .unwrap_or(DEFAULT_NAMESPACE);
        let full = format!("{namespace}.{name}");
        let methods = parse_member_definition(definition)?;
        self.types.insert(
            full.to_ascii_lowercase(),
            AddedType {
                name: full.clone(),
                methods,
            },
        );
        if named.contains_key("passthru") {
            self.emit(&full);
        }
        Ok(())
    }

    /// `[Added.Type]::Method(args)` for an `Add-Type` import: `None` when
    /// `typ` was not added by `Add-Type`.
    pub(super) fn call_added_type(
        &self,
        typ: &str,
        method: &str,
        args: &[String],
    ) -> Option<Result<String, String>> {
        let added = self.types.get(&typ.trim().to_ascii_lowercase())?;
        let Some((dll, name)) = added
            .methods
            .iter()
            .find(|(_, n)| n.eq_ignore_ascii_case(method))
        else {
            return Some(Err(format!(
                "method {method} is not defined on [{}]",
                added.name
            )));
        };
        let number = |i: usize| -> Result<i64, String> {
            args.get(i)
                .and_then(|a| parse_number(a))
                .map(|n| n as i64)
                .ok_or_else(|| format!("{name}: argument {} must be a number", i + 1))
        };
        Some(match (dll.as_str(), name.to_ascii_lowercase().as_str()) {
            ("kernel32.dll", "isprocessorfeaturepresent") => number(0).map(|feature| {
                bool_string(crate::system_profile::processor_feature_present(feature as u32))
            }),
            // Broadcasting WM_SETTINGCHANGE tells running programs the
            // environment changed; guest sessions read it at start (or on
            // `reload`), so the broadcast succeeds with nothing to notify.
            ("user32.dll", "sendmessagetimeout" | "sendmessagetimeoutw" | "sendmessagetimeouta") => {
                Ok("1".to_string())
            }
            ("kernel32.dll", "getcurrentprocessid") => Ok(std::process::id().to_string()),
            _ => Err(format!("P/Invoke {dll}!{name} is not supported")),
        })
    }

    /// Whether `[typ]` names a type: built-in ones, `Add-Type` additions,
    /// and the registry enums.
    pub(super) fn type_exists(&self, typ: &str) -> bool {
        let t = bare_type(typ);
        KNOWN_TYPES.contains(&t.as_str())
            || self.types.contains_key(&typ.trim().to_ascii_lowercase())
            || registry::enum_member(typ, "None").is_some()
    }

    /// `[typ] value`: convert like PowerShell, or fail.
    pub(super) fn cast_value(&self, typ: &str, value: Value) -> Result<Value, String> {
        let t = bare_type(typ);
        let text = value_string(&value);
        let fail = || format!("Cannot convert value \"{text}\" to type \"{typ}\".");
        Ok(match t.as_str() {
            "ref" | "object" | "array" | "psobject" => value,
            "string" => Value::Str(text),
            "bool" | "boolean" => Value::Str(bool_string(is_truthy(&text))),
            "int" | "int32" | "long" | "int64" | "uint32" | "uint64" | "byte" | "intptr"
            | "uintptr" | "int16" | "uint16" | "sbyte" => {
                let n = parse_number(&text).ok_or_else(fail)?;
                let n = n.round();
                let fits = match t.as_str() {
                    "int" | "int32" => i32::try_from(n as i64).is_ok(),
                    "uint32" => u32::try_from(n as i64).is_ok(),
                    "byte" => u8::try_from(n as i64).is_ok(),
                    "int16" => i16::try_from(n as i64).is_ok(),
                    "uint16" => u16::try_from(n as i64).is_ok(),
                    "sbyte" => i8::try_from(n as i64).is_ok(),
                    "uint64" | "uintptr" => n >= 0.0,
                    _ => true,
                };
                if !fits {
                    return Err(fail());
                }
                Value::Str((n as i64).to_string())
            }
            "double" | "single" | "float" | "decimal" => {
                let n = parse_number(&text).ok_or_else(fail)?;
                Value::Str(n.to_string())
            }
            // Numbers are code points (`[char]27`); one character is itself.
            "char" => match parse_number(&text) {
                Some(n) => Value::Str(char::from_u32(n as u32).ok_or_else(fail)?.to_string()),
                None if text.chars().count() == 1 => Value::Str(text),
                None => return Err(fail()),
            },
            "type" => {
                if self.type_exists(&text) {
                    Value::Str(text)
                } else {
                    return Err(fail());
                }
            }
            _ => return Err(format!("casts to [{typ}] are not supported")),
        })
    }

    /// `value -as [typ]`: the converted value, or `$null` (empty).
    pub(super) fn as_value(&self, typ: &str, value: Value) -> Value {
        self.cast_value(typ, value)
            .unwrap_or_else(|_| Value::Str(String::new()))
    }

    /// Evaluate `[T] value` / `[T]value` / `value -as [T]` token runs;
    /// `None` when `toks` is not such an expression.
    pub(super) fn eval_conversion(&mut self, toks: &[Token]) -> Result<Option<Value>, String> {
        if toks.is_empty() {
            return Ok(None);
        }
        if toks.len() == 3 && !toks[1].quoted && toks[1].text().eq_ignore_ascii_case("-as") {
            if let Some(typ) = type_literal(&toks[2].text()) {
                let typ = typ.to_string();
                let (v, _) = self.eval_value(&toks[..1])?;
                return Ok(Some(self.as_value(&typ, v)));
            }
        }
        if toks[0].chars.first() != Some(&('[', true)) {
            return Ok(None);
        }
        let head = toks[0].text();
        if let Some(typ) = type_literal(&head) {
            if toks.len() >= 2 {
                let typ = typ.to_string();
                let (v, _) = self.eval_value(&toks[1..])?;
                return self.cast_value(&typ, v).map(Some);
            }
            return Ok(None);
        }
        if toks.len() == 1 {
            if let Some((typ, rest)) = attached_cast(&head) {
                let (typ, rest) = (typ.to_string(), rest.to_string());
                let rest_toks = tokenize(&rest)?;
                let (v, _) = self.eval_value(&rest_toks)?;
                return self.cast_value(&typ, v).map(Some);
            }
        }
        Ok(None)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn member_definitions_list_their_imports() {
        let methods = parse_member_definition(
            "[DllImport(\"user32.dll\", SetLastError = true)]\npublic static extern IntPtr SendMessageTimeout(IntPtr h);\n[DllImport(\"KERNEL32\")] public static extern bool IsProcessorFeaturePresent(int f);",
        )
        .unwrap();
        assert_eq!(
            methods,
            vec![
                ("user32.dll".to_string(), "SendMessageTimeout".to_string()),
                ("kernel32.dll".to_string(), "IsProcessorFeaturePresent".to_string()),
            ]
        );
        assert!(parse_member_definition("public static int Add(int a) { return a; }").is_err());
        assert!(parse_member_definition("[DllImport(\"x.dll\")] int nope;").is_err());
    }

    #[test]
    fn type_literals_and_attached_casts() {
        assert_eq!(type_literal("[Type]"), Some("Type"));
        assert_eq!(type_literal("[string[]]"), Some("string[]"));
        assert_eq!(type_literal("[Win32.NativeMethods]"), Some("Win32.NativeMethods"));
        assert_eq!(type_literal("[a b]"), None);
        assert_eq!(attached_cast("[char]27"), Some(("char", "27")));
        assert_eq!(attached_cast("[T]::Member"), None);
        assert_eq!(attached_cast("[T]"), None);
    }
}
